In [2]:
import numpy as np

Vectores

In [4]:
v = np.array([1,2,3,-1])
w = np.array([2,3,0,5])

print("v + w = ", v+w)
print("2 * v = ", 2*v)
print("v^2 = ", v**2)


v + w =  [3 5 3 4]
2 * v =  [ 2  4  6 -2]
v^2 =  [1 4 9 1]


Matrices

In [15]:
A = np.array([[1,2,3,4,5],[0,4,2,9,6],[12,-1,9,5,7],[9,0,-3,0,8]])
print(A)

A[0:2,3:5]                  # Desde fila 0 hasta fila 2 (sin incluir), desde columna 3 hasta la 5 (sin incluir)
A[:2,3:]                    # Todo hasta fila 2, todo desde columna 3
A[[0,2,3],:]                # fila 0, 2 y 3, todo
ind = np.array([0,2,3])     
A[ind,ind]                  # Coordenada a coordenada: [0,2,3],[0,2,3] = (0,0), (2,2), (3,3)
A[ind, ind[:,None]]



[[ 1  2  3  4  5]
 [ 0  4  2  9  6]
 [12 -1  9  5  7]
 [ 9  0 -3  0  8]]


array([[ 1, 12,  9],
       [ 3,  9, -3],
       [ 4,  5,  0]])

Numeros Complejos

In [25]:
1j*1j
(1+2j)*1j
z = 1 + 2j
w = 3 - 3j
print("z + w =", z+w)
print(f"Parte Real: {w.real}\nParte Imaginaria: {w.imag}")
print(f"Conjugado: {w.conjugate()}")
w_= w.conjugate()
print(f"w * w_ = {w*w_}")

z + w = (4-1j)
Parte Real: 3.0
Parte Imaginaria: -3.0
Conjugado: (3+3j)
w * w_ = (18+0j)
