In [7]:
import numpy as np
import scipy as sp

Ejercicio 3

In [13]:
def solve_LU(L, U, b):
    y = sp.linalg.solve_triangular(L,b, lower=True)
    x = sp.linalg.solve_triangular(U, y)
    return x

In [3]:
def desc_LU(A):
    rows, cols = A.shape
    L = np.eye(rows)
    U = A.copy()

    if rows != cols:
        raise ValueError("La matriz debe ser cuadrada para realizar la descomposición LU.")
    
    for i in range(rows):
        for j in range(i+1,rows):
            factor = U[j,i]/U[i,i]                           #Calculo el factor por el cual modifico la fila a escalonar
            U[j,i:] = U[j,i:] - factor * U[i,i:]             #Le resto a la fila j de U la fila i multiplicada por el factor que la escalona
            L[j,i] = factor                                  #Armo L que es los factores como columnas de bajo de la diagonal con el signo opuesto
           
    return L, U

A = np.array([[2,1,2,3],[4,3,3,4],[-2,2,-4, -12],[4,1,8,-3]])
if np.linalg.det(A) != 0:
    L, U = desc_LU(A)
    print("Matriz A:\n", A)
    print("Matriz L:\n",L)
    print("Matriz U:\n",U)
    print("A = LU:\n", L@U)
else:
    print("A has no inverse")

Matriz A:
 [[  2   1   2   3]
 [  4   3   3   4]
 [ -2   2  -4 -12]
 [  4   1   8  -3]]
Matriz L:
 [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [-1.  3.  1.  0.]
 [ 2. -1.  3.  1.]]
Matriz U:
 [[ 2  1  2  3]
 [ 0  1 -1 -2]
 [ 0  0  1 -3]
 [ 0  0  0 -2]]
A = LU:
 [[  2.   1.   2.   3.]
 [  4.   3.   3.   4.]
 [ -2.   2.  -4. -12.]
 [  4.   1.   8.  -3.]]


In [32]:
def resolve_system(A, b):
    L, U = desc_LU(A)
    return solve_LU(L, U, b)

A = np.array([[1,-1,0,1],[0,1,4,0],[2,-1,0,-2],[-3,3,0,-1]])
b = np.array([1,-7,-5,1])

resolve_system(A,b)

array([ 0.,  1., -2.,  2.])

In [14]:
def calcular_inv(A):
    rows, cols = A.shape
    b = np.eye(rows)
    L, U = desc_LU(A)
    res = np.zeros(A.shape)
    for i in range(rows):
        res[:,i] = solve_LU(L,U, b[:,i])

    return res

A = np.array([[1,-1,0,1],[0,1,4,0],[2,-1,0,-2],[-3,3,0,-1]])
print(calcular_inv(A))

print(np.linalg.inv(A))

[[ 3.5   0.    1.    1.5 ]
 [ 4.    0.    1.    2.  ]
 [-1.    0.25 -0.25 -0.5 ]
 [ 1.5   0.    0.    0.5 ]]
[[ 3.5  -0.    1.    1.5 ]
 [ 4.    0.    1.    2.  ]
 [-1.    0.25 -0.25 -0.5 ]
 [ 1.5   0.    0.    0.5 ]]
