In [1]:
import numpy as np

Ejercicio 3

In [8]:
def solve_LU(L, U, b):
    y = np.linalg.solve(L,b)
    x = np.linalg.solve(U, y)
    return x

In [36]:
def desc_LU(A):
    rows, cols = A.shape
    M = np.eye(rows)
    for i in range(cols):
        M_i = np.eye(rows)
        
        for j in range(i+1,rows):
            
            factor = - (A[j,i]/A[i,i])
            M_i[j,i] = factor
        
        M = M_i@M
        A = M@A
     
    return M

A = np.array([[2,1,2,3],[4,3,3,4],[-2,2,-4, -12],[4,1,8,-3]])
M = desc_LU(A)
print(A)
U = M@A
np.linalg.inv(M)@U

[[  2   1   2   3]
 [  4   3   3   4]
 [ -2   2  -4 -12]
 [  4   1   8  -3]]


array([[  2.,   1.,   2.,   3.],
       [  4.,   3.,   3.,   4.],
       [ -2.,   2.,  -4., -12.],
       [  4.,   1.,   8.,  -3.]])